=== adrianaherreroglez/MotoGP-Desktop/xml/circuito.dtd
<!ELEMENT circuito (
    nombre,
    longitud,
    anchuraMedia,
    fecha,
    horaInicio,
    vueltas,
    localidad,
    pais,
    patrocinador,
    referencias,
    galeriaFotografias,
    galeriaVideos,
    puntoOrigen,
    tramos,
    vencedor,
    clasificados
)>

<!ELEMENT nombre (#PCDATA)>

<!ELEMENT longitud (#PCDATA)>
<!ATTLIST longitud unidad CDATA #REQUIRED>

<!ELEMENT anchuraMedia (#PCDATA)>
<!ATTLIST anchuraMedia unidad CDATA #REQUIRED>

<!ELEMENT fecha (#PCDATA)>
<!ELEMENT horaInicio (#PCDATA)> 
<!ELEMENT vueltas (#PCDATA)>
<!ELEMENT localidad (#PCDATA)>
<!ELEMENT pais (#PCDATA)>
<!ELEMENT patrocinador (#PCDATA)>

<!-- referencias: al menos 3 referencias -->
<!ELEMENT referencias (referencia, referencia, referencia, referencia*)>
<!ELEMENT referencia (#PCDATA)>

<!-- galeriaFotografias: 1..5 fotos -->
<!ELEMENT galeriaFotografias (foto, foto?, foto?, foto?, foto?)>
<!ELEMENT foto (#PCDATA)>

<!-- galeriaVideos: 1..3 videos -->
<!ELEMENT galeriaVideos (video, video?, video?)>
<!ELEMENT video (#PCDATA)>

<!ELEMENT puntoOrigen (longitudOrigen, latitud, altitud)>
<!ELEMENT longitudOrigen (#PCDATA)>
<!ELEMENT latitud (#PCDATA)>
<!ELEMENT altitud (#PCDATA)>
<!ELEMENT tramos (tramo+)>
<!ELEMENT tramo (distancia, coordenadas, numeroSector)>
<!ELEMENT distancia (#PCDATA)>
<!ATTLIST distancia unidad CDATA #REQUIRED>
<!ELEMENT coordenadas (longitudPunto, latitudPunto, altitudPunto)>
<!ELEMENT longitudPunto (#PCDATA)>
<!ELEMENT latitudPunto (#PCDATA)>
<!ELEMENT altitudPunto (#PCDATA)>
<!ELEMENT numeroSector (#PCDATA)>
<!ELEMENT vencedor (nombrePiloto, tiempo)>
<!ELEMENT nombrePiloto (#PCDATA)>
<!ELEMENT tiempo (#PCDATA)>
<!ELEMENT clasificados (primero, segundo, tercero)>
<!ELEMENT primero (#PCDATA)>
<!ELEMENT segundo (#PCDATA)>
<!ELEMENT tercero (#PCDATA)>

=== adrianaherreroglez/MotoGP-Desktop/xml/circuito.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE circuito SYSTEM "circuito.dtd">
<circuito>
    <nombre>Losail International Circuit</nombre>
    <longitud unidad="m">5380</longitud>
    <anchuraMedia unidad="m">12</anchuraMedia>
    <fecha>2025-04-13</fecha>
    <horaInicio>19:00</horaInicio>
    <vueltas>22</vueltas>
    <localidad>Losail</localidad>
    <pais>Qatar</pais>
    <patrocinador>Qatar Airways</patrocinador>
    <referencias>
        <referencia>
            https://www.motogp.com/en/calendar/2025/event/qatar/7a40caf3-8e8f-4405-b6e7-702453149285?tab=overview</referencia>
        <referencia>https://es.wikipedia.org/wiki/Circuito_Internacional_de_Losail</referencia>
        <referencia>https://www.qatarmotogp.com/</referencia>
        <referencia>https://www.lcsc.qa/en/24/Event/2025-MOTOGP-QATAR-AIRWAYS-GRAND-PRIX-OF-QATAR</referencia>
    </referencias>
    <galeriaFotografias>
        <foto>multimedia/gradas.jpg</foto>
        <foto>multimedia/nombreCircuito.jpg</foto>
        <foto>multimedia/salidaCircuito.jpg</foto>
        <foto>multimedia/vistaAereaNocturna.jpg</foto>
    </galeriaFotografias>
    <galeriaVideos>
        <video>multimedia/promoQatar.mp4</video>
        <video>multimedia/videoQatar.mp4</video>
    </galeriaVideos>
    
    <puntoOrigen>
        <longitudOrigen>51.44906788509163</longitudOrigen>
        <latitud>25.48982940961587</latitud>
        <altitud>11.55652153703528</altitud>
    </puntoOrigen>

    <tramos>
        <!--SECTOR 1-->
        <tramo>
            <!--inicio-->
            <distancia unidad="m">0</distancia>
            <coordenadas>
                <longitudPunto>51.44906788509163</longitudPunto>
                <latitudPunto>25.48982940961587</latitudPunto>
                <altitudPunto>11.55652153703528</altitudPunto>
            </coordenadas>
            <numeroSector>1</numeroSector>
        </tramo>
        <!--a1-->
        <tramo>
            <distancia unidad="m">0</distancia>
            <coordenadas>
                <longitudPunto>51.45211154693168</longitudPunto>
                <latitudPunto>25.48483165445843</latitudPunto>
                <altitudPunto>14.48034983932676</altitudPunto>
            </coordenadas>
            <numeroSector>1</numeroSector>
        </tramo>
        <!--a2-->
        <tramo>
            <distancia unidad="m">0</distancia>
            <coordenadas>
                <longitudPunto>51.45301068947162</longitudPunto>
                <latitudPunto>25.48419935683365</latitudPunto>
                <altitudPunto>12.91849688021095</altitudPunto>
            </coordenadas>
            <numeroSector>1</numeroSector>
        </tramo>
        <!--a3-->
        <tramo>
            <distancia unidad="m">0</distancia>
            <coordenadas>
                <longitudPunto>51.45272305685405</longitudPunto>
                <latitudPunto>25.48438423182126</latitudPunto>
                <altitudPunto>13.66830450713548</altitudPunto>
            </coordenadas>
            <numeroSector>1</numeroSector>
        </tramo>
        <!--a4-->
        <tramo>
            <distancia unidad="m">0</distancia>
            <coordenadas>
                <longitudPunto>51.45581169455631</longitudPunto>
                <latitudPunto>25.48732047615447</latitudPunto>
                <altitudPunto>12.68435758065745</altitudPunto>
            </coordenadas>
            <numeroSector>1</numeroSector>
        </tramo>
         <!--a5-->
        <tramo>
            <distancia unidad="m">0</distancia>
            <coordenadas>
                <longitudPunto>51.45597159352693</longitudPunto>
                <latitudPunto>25.48737882559786</latitudPunto>
                <altitudPunto>12.99931974666785</altitudPunto>
            </coordenadas>
            <numeroSector>1</numeroSector>
        </tramo>
         <!--a6-->
        <tramo>
            <distancia unidad="m">0</distancia>
            <coordenadas>
                <longitudPunto>51.45873940421528</longitudPunto>
                <latitudPunto>25.48716051363366</latitudPunto>
                <altitudPunto>13.03530779079563</altitudPunto>
            </coordenadas>
            <numeroSector>1</numeroSector>
        </tramo>
         <!--a7-->
        <tramo>
            <distancia unidad="m">0</distancia>
            <coordenadas>
                <longitudPunto>51.45870743757185</longitudPunto>
                <latitudPunto>25.48716326186229</latitudPunto>
                <altitudPunto>13.26400052284275</altitudPunto>
            </coordenadas>
            <numeroSector>1</numeroSector>
        </tramo>
        <!--a8-->
        <tramo>
            <distancia unidad="m">0</distancia>
            <coordenadas>
                <longitudPunto>51.4598665541052</longitudPunto>
                <latitudPunto>25.4885349910928</latitudPunto>
                <altitudPunto>11.55637413916006</altitudPunto>
            </coordenadas>
            <numeroSector>1</numeroSector>
        </tramo>
        <!--a9-->
        <tramo>
            <distancia unidad="m">0</distancia>
            <coordenadas>
                <longitudPunto>51.46005266382088</longitudPunto>
                <latitudPunto>25.48884131427337</latitudPunto>
                <altitudPunto>12.16924615650678</altitudPunto>
            </coordenadas>
            <numeroSector>1</numeroSector>
        </tramo>
        <!--a10-->
        <tramo>
            <distancia unidad="m">0</distancia>
            <coordenadas>
                <longitudPunto>51.45920578267339</longitudPunto>
                <latitudPunto>25.4894095196156</latitudPunto>
                <altitudPunto>11.33848925721772</altitudPunto>
            </coordenadas>
            <numeroSector>1</numeroSector>
        </tramo>
        <!--a11-->
        <tramo>
            <distancia unidad="m">0</distancia>
            <coordenadas>
                <longitudPunto>51.45920578267339</longitudPunto>
                <latitudPunto>25.4894095196156</latitudPunto>
                <altitudPunto>11.33848925721772</altitudPunto>
            </coordenadas>
            <numeroSector>1</numeroSector>
        </tramo>


        

    </tramos>
    <vencedor>
        <nombrePiloto>Marc Márquez</nombrePiloto>
        <tiempo>00:41:29.186</tiempo>
    </vencedor>
    <clasificados>
        <primero>Marc Márquez</primero>
        <segundo>Francesco Bagnaia</segundo>
        <tercero>Franco Morbidelli</tercero>
    </clasificados>
</circuito>
