=== adrianaherreroglez/MotoGP-Desktop/xml/circuito.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns="http://www.uniovi.es" elementFormDefault="qualified" targetNamespace="http://www.uniovi.es" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="circuito">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="nombre" />
				<xs:element ref="longitud" />
				<xs:element ref="anchuraMedia" />
				<xs:element ref="fecha" />
				<xs:element ref="horaInicio" />
				<xs:element ref="vueltas" />
				<xs:element ref="localidad" />
				<xs:element ref="pais" />
				<xs:element ref="patrocinador" />
				<xs:element ref="referencias" />
				<xs:element ref="galeriaFotografias" />
				<xs:element ref="galeriaVideos" />
				<xs:element ref="puntoOrigen" />
				<xs:element ref="tramos" />
				<xs:element ref="vencedor" />
				<xs:element ref="clasificados" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="nombre" type="xs:string" />
	<xs:element name="longitud">
        <xs:complexType>
            <xs:simpleContent>
                <xs:extension base="longitudType">
                    <xs:attribute name="unidad" type="xs:string" use="required" />
                </xs:extension>
            </xs:simpleContent>
        </xs:complexType>
    </xs:element>
    <xs:simpleType name="longitudType">
        <xs:restriction base="xs:float">
            <xs:minInclusive value="1"/>
            <xs:maxInclusive value="10000"/>
        </xs:restriction>
    </xs:simpleType>

	 <xs:element name="anchuraMedia">
        <xs:complexType>
            <xs:simpleContent>
                <xs:extension base="anchuraMediaType">
                    <xs:attribute name="unidad" type="xs:string" use="required" />
                </xs:extension>
            </xs:simpleContent>
        </xs:complexType>
    </xs:element>
    <xs:simpleType name="anchuraMediaType">
        <xs:restriction base="xs:float">
            <xs:minInclusive value="1"/>
            <xs:maxInclusive value="200"/>
        </xs:restriction>
    </xs:simpleType>

	<xs:element name="fecha" type="xs:date" />
	<xs:element name="horaInicio" type="xs:time" />

	<xs:element name="vueltas" type="vueltasType" />
    <xs:simpleType name="vueltasType">
        <xs:restriction base="xs:positiveInteger">
            <xs:minInclusive value="1"/>
            <xs:maxInclusive value="150"/>
        </xs:restriction>
    </xs:simpleType>

	<xs:element name="localidad" type="xs:string" />
	<xs:element name="pais" type="xs:string" />
	<xs:element name="patrocinador" type="xs:string" />
	<xs:element name="referencias">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="3" maxOccurs="unbounded" ref="referencia" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="referencia" type="xs:string" />
	<xs:element name="galeriaFotografias">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="1" maxOccurs="5" ref="foto" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="foto" type="xs:string" />
	<xs:element name="galeriaVideos">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="1" maxOccurs="3" ref="video" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="video" type="xs:string" />

	 <xs:simpleType name="longitudGeoType">
        <xs:restriction base="xs:float">
            <xs:minInclusive value="-180"/>
            <xs:maxInclusive value="180"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="latitudGeoType">
        <xs:restriction base="xs:float">
            <xs:minInclusive value="-90"/>
            <xs:maxInclusive value="90"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="altitudGeoType">
        <xs:restriction base="xs:float">
            <xs:minInclusive value="-500"/>
            <xs:maxInclusive value="9000"/>
        </xs:restriction>
    </xs:simpleType>

	<xs:element name="puntoOrigen">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="longitudOrigen" />
				<xs:element ref="latitud" />
				<xs:element ref="altitud" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="longitudOrigen" type="longitudGeoType" />
    <xs:element name="latitud" type="latitudGeoType" />
    <xs:element name="altitud" type="altitudGeoType" />
	<xs:element name="tramos">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="1" maxOccurs="unbounded" ref="tramo" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="tramo">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="distancia" />
				<xs:element ref="coordenadas" />
				<xs:element ref="numeroSector" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="distancia">
        <xs:complexType>
            <xs:simpleContent>
                <xs:extension base="distanciaType">
                    <xs:attribute name="unidad" type="xs:string" use="required" />
                </xs:extension>
            </xs:simpleContent>
        </xs:complexType>
    </xs:element>
    <xs:simpleType name="distanciaType">
        <xs:restriction base="xs:float">
            <xs:minInclusive value="1"/>
            <xs:maxInclusive value="1000"/>
        </xs:restriction>
    </xs:simpleType>

	<xs:element name="coordenadas">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="longitudPunto" />
				<xs:element ref="latitudPunto" />
				<xs:element ref="altitudPunto" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="longitudPunto" type="longitudGeoType" />
    <xs:element name="latitudPunto" type="latitudGeoType" />
    <xs:element name="altitudPunto" type="altitudGeoType" />

	<xs:element name="numeroSector" type="numeroSectorType" />
    <xs:simpleType name="numeroSectorType">
        <xs:restriction base="xs:positiveInteger">
            <xs:minInclusive value="1"/>
            <xs:maxInclusive value="15"/>
        </xs:restriction>
    </xs:simpleType>

	<xs:element name="vencedor">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="nombrePiloto" />
				<xs:element ref="tiempo" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="nombrePiloto" type="xs:string" />
	<xs:element name="tiempo" type="xs:time" />
	<xs:element name="clasificados">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="primero" />
				<xs:element ref="segundo" />
				<xs:element ref="tercero" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="primero" type="xs:string" />
	<xs:element name="segundo" type="xs:string" />
	<xs:element name="tercero" type="xs:string" />
</xs:schema>

=== adrianaherreroglez/MotoGP-Desktop/xml/circuitoEsquema.xml
<?xml version="1.0" encoding="UTF-8"?>
<circuito xmlns="http://www.uniovi.es" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.uniovi.es circuito.xsd">
    <nombre>Losail International Circuit</nombre>
    <longitud unidad="m">5380</longitud>
    <anchuraMedia unidad="m">12</anchuraMedia>
    <fecha>2025-04-13</fecha>
    <horaInicio>19:00:00</horaInicio>
    <vueltas>22</vueltas>
    <localidad>Losail</localidad>
    <pais>Qatar</pais>
    <patrocinador>Qatar Airways</patrocinador>
    <referencias>
        <referencia>
            https://www.motogp.com/en/calendar/2025/event/qatar/7a40caf3-8e8f-4405-b6e7-702453149285?tab=overview</referencia>
        <referencia>https://es.wikipedia.org/wiki/Circuito_Internacional_de_Losail</referencia>
        <referencia>https://www.qatarmotogp.com/</referencia>
        <referencia>https://www.lcsc.qa/en/24/Event/2025-MOTOGP-QATAR-AIRWAYS-GRAND-PRIX-OF-QATAR</referencia>
    </referencias>
    <galeriaFotografias>
        <foto>multimedia/gradas.jpg</foto>
        <foto>multimedia/nombreCircuito.jpg</foto>
        <foto>multimedia/salidaCircuito.jpg</foto>
        <foto>multimedia/vistaAereaNocturna.jpg</foto>
    </galeriaFotografias>
    <galeriaVideos>
        <video>multimedia/promoQatar.mp4</video>
        <video>multimedia/videoQatar.mp4</video>
    </galeriaVideos>

    <puntoOrigen>
        <longitudOrigen>25.48928989802003</longitudOrigen>
        <latitud>51.44953333968715</latitud>
        <altitud>11.89460338104143</altitud>
    </puntoOrigen>

    <tramos>
        <!--SECTOR 1-->
        <!--a1-->
        <tramo>
            <distancia unidad="m">659.17</distancia>
            <coordenadas>
                <longitudPunto>25.48412347985424</longitudPunto>
                <latitudPunto>51.45275035532733</latitudPunto>
                <altitudPunto>13.9122054592293</altitudPunto>
            </coordenadas>
            <numeroSector>1</numeroSector>
        </tramo>

        <!--a2-->
        <tramo>
            <distancia unidad="m">65.21</distancia>
            <coordenadas>
                <longitudPunto>25.48379988766239</longitudPunto>
                <latitudPunto>51.45329068603851</latitudPunto>
                <altitudPunto>13.30685747573334</altitudPunto>
            </coordenadas>
            <numeroSector>1</numeroSector>
        </tramo>

        <!--a3-->
        <tramo>
            <distancia unidad="m">56.04</distancia>
            <coordenadas>
                <longitudPunto>25.4840703464576</longitudPunto>
                <latitudPunto>51.45376210297766</latitudPunto>
                <altitudPunto>13.0164405006168</altitudPunto>
            </coordenadas>
            <numeroSector>1</numeroSector>
        </tramo>

        <!--a4-->
        <tramo>
            <distancia unidad="m">382.97</distancia>
            <coordenadas>
                <longitudPunto>25.48714078286195</longitudPunto>
                <latitudPunto>51.45551799130361</latitudPunto>
                <altitudPunto>12.53340872716946</altitudPunto>
            </coordenadas>
            <numeroSector>1</numeroSector>
        </tramo>

        <!--a5-->
        <tramo>
            <distancia unidad="m">53.98</distancia>
            <coordenadas>
                <longitudPunto>25.48734189327791</longitudPunto>
                <latitudPunto>51.45600739332009</latitudPunto>
                <altitudPunto>12.85661087351182</altitudPunto>
            </coordenadas>
            <numeroSector>1</numeroSector>
        </tramo>

        <!--a6-->
        <tramo>
            <distancia unidad="m">267.36</distancia>
            <coordenadas>
                <longitudPunto>25.48687499910984</longitudPunto>
                <latitudPunto>51.45861589856321</latitudPunto>
                <altitudPunto>13.31601833134279</altitudPunto>
            </coordenadas>
            <numeroSector>1</numeroSector>
        </tramo>

        <!--a7-->
        <tramo>
            <distancia unidad="m">50.69</distancia>
            <coordenadas>
                <longitudPunto>25.4870408245405</longitudPunto>
                <latitudPunto>51.45908622747559</latitudPunto>
                <altitudPunto>12.90185774613854</altitudPunto>
            </coordenadas>
            <numeroSector>1</numeroSector>
        </tramo>

        <!--a8-->
        <tramo>
            <distancia unidad="m">171.74</distancia>
            <coordenadas>
                <longitudPunto>25.4885349910928</longitudPunto>
                <latitudPunto>51.4598665541052</latitudPunto>
                <altitudPunto>11.55637413916006</altitudPunto>
            </coordenadas>
            <numeroSector>1</numeroSector>
        </tramo>

        <!--a9-->
        <tramo>
            <distancia unidad="m">37.4</distancia>
            <coordenadas>
                <longitudPunto>25.48870484701892</longitudPunto>
                <latitudPunto>51.45995752364238</latitudPunto>
                <altitudPunto>11.69765855333102</altitudPunto>
            </coordenadas>
            <numeroSector>1</numeroSector>
        </tramo>

        <!--a10-->
        <tramo>
            <distancia unidad="m">142.73</distancia>
            <coordenadas>
                <longitudPunto>25.48981854803052</longitudPunto>
                <latitudPunto>51.45924383251973</latitudPunto>
                <altitudPunto>11.83666014089355</altitudPunto>
            </coordenadas>
            <numeroSector>1</numeroSector>
        </tramo>

        <!--a11-->
        <tramo>
            <distancia unidad="m">60.04</distancia>
            <coordenadas>
                <longitudPunto>25.49002431589926</longitudPunto>
                <latitudPunto>51.45869063995323</latitudPunto>
                <altitudPunto>12.07837645712428</altitudPunto>
            </coordenadas>
            <numeroSector>1</numeroSector>
        </tramo>
        <!--SECTOR 2-->
        <!--b1-->
        <tramo>
            <distancia unidad="m">284.46</distancia>
            <coordenadas>
                <longitudPunto>25.48978709616726</longitudPunto>
                <latitudPunto>51.45588158841028</latitudPunto>
                <altitudPunto>12.50473178401551</altitudPunto>
            </coordenadas>
            <numeroSector>2</numeroSector>
        </tramo>

        <!--b2-->
        <tramo>
            <distancia unidad="m">90.42</distancia>
            <coordenadas>
                <longitudPunto>25.48997320807358</longitudPunto>
                <latitudPunto>51.45500894644589</latitudPunto>
                <altitudPunto>11.64427061541766</altitudPunto>
            </coordenadas>
            <numeroSector>2</numeroSector>
        </tramo>

        <!--b3-->
        <tramo>
            <distancia unidad="m">176.34</distancia>
            <coordenadas>
                <longitudPunto>25.49092687447989</longitudPunto>
                <latitudPunto>51.45360210333502</latitudPunto>
                <altitudPunto>11.36770340178379</altitudPunto>
            </coordenadas>
            <numeroSector>2</numeroSector>
        </tramo>

        <!--b4-->
        <tramo>
            <distancia unidad="m">36.94</distancia>
            <coordenadas>
                <longitudPunto>25.49126358382133</longitudPunto>
                <latitudPunto>51.45356645647286</latitudPunto>
                <altitudPunto>11.28633449519158</altitudPunto>
            </coordenadas>
            <numeroSector>2</numeroSector>
        </tramo>

        <!--b5-->
        <tramo>
            <distancia unidad="m">38.8</distancia>
            <coordenadas>
                <longitudPunto>25.49149379360832</longitudPunto>
                <latitudPunto>51.45385706029898</latitudPunto>
                <altitudPunto>10.95666710293367</altitudPunto>
            </coordenadas>
            <numeroSector>2</numeroSector>
        </tramo>

        <!--b6-->
        <tramo>
            <distancia unidad="m">157.83</distancia>
            <coordenadas>
                <longitudPunto>25.49184740658584</longitudPunto>
                <latitudPunto>51.45537658386909</latitudPunto>
                <altitudPunto>11.2280342317395</altitudPunto>
            </coordenadas>
            <numeroSector>2</numeroSector>
        </tramo>

        <!--b7-->
        <tramo>
            <distancia unidad="m">57.14</distancia>
            <coordenadas>
                <longitudPunto>25.49225429108223</longitudPunto>
                <latitudPunto>51.45572464833729</latitudPunto>
                <altitudPunto>11.32736043329388</altitudPunto>
            </coordenadas>
            <numeroSector>2</numeroSector>
        </tramo>

        <!--b8-->
        <tramo>
            <distancia unidad="m">99.33</distancia>
            <coordenadas>
                <longitudPunto>25.49312037370886</longitudPunto>
                <latitudPunto>51.45599429316892</latitudPunto>
                <altitudPunto>11.05544090692283</altitudPunto>
            </coordenadas>
            <numeroSector>2</numeroSector>
        </tramo>

        <!--b9-->
        <tramo>
            <distancia unidad="m">127.95</distancia>
            <coordenadas>
                <longitudPunto>25.49398151753568</longitudPunto>
                <latitudPunto>51.45683227081981</latitudPunto>
                <altitudPunto>11.84618453284843</altitudPunto>
            </coordenadas>
            <numeroSector>2</numeroSector>
        </tramo>

        <!--b10-->
        <tramo>
            <distancia unidad="m">47.29</distancia>
            <coordenadas>
                <longitudPunto>25.49439181747378</longitudPunto>
                <latitudPunto>51.45696348017407</latitudPunto>
                <altitudPunto>11.84624436540244</altitudPunto>
            </coordenadas>
            <numeroSector>2</numeroSector>
        </tramo>

        <!--b11-->
        <tramo>
            <distancia unidad="m">28.72</distancia>
            <coordenadas>
